### ISSUE TITLE
Minetweaker and shops selling items gltich

### ISSUE THREAD

**Issue by Rozzers** [joshiejack/Harvest-Moon#104]
I have added items a shop can sell but I have encountered a few issues.

1. There are duplicates of the same items added. (causes a bit of a scroll bar)
2. Mod added items when bought, are not the correct item. (ex: copper for sale becomes pizza)

**Comment by joshiejack** [comment]
Probably related to the way i'm assigning them ids in 0.5, meaning they probably ended up with mismatched ids on server vs client, only tested mt on ssp =p. I rewrote the system in 0.6. Not going to do that for 0.5 though, so unless you made a mod to add them guess just broken for smp for now. sorry.

**Comment by GazbonicAcid** [comment]
Still experiencing this shop duplication glitch on the latest Harvest Festival version.
Screenshot of Proof - http://i.imgur.com/zBtlLWz.png

**Comment by joshiejack** [comment]
This wasn't fixed in any of the releases, so no need for proof :p

**Comment by GazbonicAcid** [comment]
welp, I had assumed this version 0.6 had been released.
Please get it done as soon as possible.
But not at the expense of leaving bugs in.
I already saw...
I had the one after you're "no need for proof" typed up before I got your reply.
You should still look at the screenshot though.
Because if the price is set to somewhere in either the tens of thousands or hundreds of thousands,
the price of that item starts going over the "buy" button's texture.
One little quark of the duplication bug though.
It only get's duped when mine/craft tweaker does it's initial script load when you log into a world.
But **_not_** when you manually reload using /mt reload
I'm going to try completely shutting down my game and see if it's still duped,,,

**Comment by majix560** [comment]
I already saw...
I had the one after you're "no need for proof" typed up before I got your reply.

**Comment by majix560** [comment]
You should still look at the screenshot though.
Because if the price is set to somewhere in either the tens of thousands or hundreds of thousands,
the price of that item starts going over the "buy" button's texture.

**Comment by majix560** [comment]
One little quark of the duplication bug though.
It only get's duped when mine/craft tweaker does it's initial script load when you log into a world.
But **_not_** when you manually reload using /mt reload

**Comment by majix560** [comment]
I'm going to try completely shutting down my game and see if it's still duped,,,

**Comment by joshiejack** [comment]
Question: Do you actually think you are helping by spamming this issue about something that has already been fixed for the next version on top of that telling me to do it "as soon as possible".

**Comment by GazbonicAcid** [comment]
Sorry....
I have no idea how to express that I feel bad now without it coming of as either fake or corny.
Edit: do you want me to purge my spam from this issue?

**Comment by joshiejack** [comment]
If ya'll want to try this one. Had a few minutes to do some 0.5 things. Didn't take too much time away from 0.6 =P

http://joshiejack.uk/mods/Harvest-Festival-1.10.2-0.5.15.jar

**Comment by themidknightson** [comment]
First thank you wholeheartedly for the mod it's fantastic. Second this issue has been on our server for awhile. We know the mod is still new so we were/are not worried about it at all. We have been patiently waiting for your next release as this is our favorite mod and I wanted to say I greatly appreciate you taking time to fix this issue in general let alone fixing it in the current version. I have mentioned how awesome of a developer you are in several of my videos lol I'm kingstenhd on YouTube BTW. Thank you and I will try out this fix now!

**Comment by joshiejack** [comment]
Rest of the things btw
![Changes](http://i.imgur.com/lOym323.png)

**Comment by Rozzers** [comment]
You're the best!!!! Hopefully this fixes the issues. Thanks Joshie.

Edit: I'm checking out the jar you sent. I only test the remove purchasable and the adjust purchasable. Adjust works, but the remove does not seem to be working. I got no minetweaker errors. I am more happy about adjustable working. Thanks again Joshie.

**Comment by GazbonicAcid** [comment]
Could you perhaps add the ability to recognize CustomNPC's npc's as Harvest Festival npc's specifically for the purpose of attaching your CraftTweaker custom shop support to them?
I don't care about any other CustomNPC's mod support now.
Just want either the ability to attach Harvest Festival custom shop CraftTweaker script to a CustomNPC npc,
or the ability to create custom HF npc's.
For the latter option perhaps you could give players a quick and dirty command to copy/paste an existing npc to new name and store such npc's in an "external" out-of-game config/folder.

**Comment by joshiejack** [comment]
Neither of those would be quick and easy, so if i do it would be in later
version. Adding support for a custom hf  npc would be a lot. You have to
specify skin, birthday, age group, all sorts of greetings and a bunch more
just a few things off the top of my head. As for customnpc support I'd have
to pretty much overwrite their right click handler, but id also have to
look at their code to work out how they differentiate a npc, so I'd know
which to open the gui for, plus I'd have to rewrite parts of the gui code
that rely on it being my npc, for example i set a settalking flag on my
npcs to false when closing shops. So would have to rewrite that tio add a
bunch of checks same with just opening the gui, since i get the shop from
the npc data.

**Comment by joshiejack** [comment]
But yea as a custom npc with hf would require skin and lang, that would be
better off as it's own system. I'll look in to it when I'm done with rest
of 0.6 update, would want to allow for custom buildings too =).
