### ISSUE TITLE
General Performance Issues

### ISSUE THREAD

**Issue by DeliciousTea** [joshiejack/Harvest-Moon#113]
Harvest Festival Version: 0.5.14
Forge Version:  2166

So I've been playing with Harvest Festival for a week or so on my server and I've noticed some serious performance problems: dropped ticks, erratic entity movement, etc and I've been trying to figure it out. I removed Harvest Festival today and the problems stopped. I love this mod but I'm guessing it just does too much for it to work nicely with a modestly sized mod pack (70 mods). Such a bummer.

For reference: our server is no slouch, it's a core i-7 2600 with 16gb of RAM dedicated hardware.

Anyway, love the mod, wish we could use it on our server!

**Comment by joshiejack** [comment]
You'll have to be more specific about which parts you're having issues with. By the nature of the mod of course removing it will improve things slightly since it's affecting how the world looks, with time,and seasons.
And you'll also have a daily performance drop as it does everything it needs to at once. However it has not impacted playability at all for me.
Any decrease is incredibly minor and unnoticed. (for me personally and some others) So you'd have to inform me what's affecting you personally the most.  Can't just guess. What the issue is. Will need evidence provided ^_^.

**Comment by P3rf3ctXZer0** [comment]
I have to reference my own issue since I believe if seasons are calling that many ticks maybe some users would be better off not running it. 

https://github.com/PenguinSquad/Harvest-Festival/issues/114
