### ISSUE TITLE
Dead bush unbreakable

### ISSUE THREAD

**Issue by xenoflot** [joshiejack/Harvest-Moon#117]
harvestfestival-1.10.2-0.5.21

Some seeds were neglected and turned into Dead Bushes :( Unfortunately I can't seem to break them at all. Tried pick, axe and hoe. I needed to dig out adjacent blocks and then dig out the dirt underneath.

**Comment by GirafiStudios** [comment]
You need a sickle to break it.

**Comment by xenoflot** [comment]
@GirafiStudios 

Perhaps a WAILA/TheOneProbe tooltip could be added then? TOP currently reports "Pickaxe" as the appropriate tool.
It didn't occur to me to go looking through JEI for alternative tools that might be able to break it!

**Comment by joshiejack** [comment]
Jade actually tells you that the sickle is what you use to break dead crops.
"As a last reward, take this sickle. You'll need it to harvest some crops, and it is pretty effective at destroying dead ones!"

I don't like WAILA/TOP so there won't be any support for them.

**Comment by joshiejack** [comment]
On top of that in the 0.6 update I've added a book with notes like this ![Notes Preview](https://cdn.discordapp.com/attachments/227497118498029569/259939297577271296/unknown.png)

And have an entry for the sickle explaining it. Once you receive it that reads
"The sickle is a tool that is very effective at destroying crops, and other plant like matter. It is especially effective at destroying any of your crops that may end up dying from lack of water or season changes. \n\nSome crops such as grass or wheat require the use of the sickle in order to harvest their drops."

So hopefully if people pay attention/read xD.

**Comment by xenoflot** [comment]
Oh cool. Actually a manual was the first thing I looked for but apparently isn't in the version I have :-)

On the WAILA/TOP issue... you may not like them, but your customers/audience seem to. Even if you don't personally use those tools, having support for them will have an effect (small but there) on the popularity/acceptance of your mod.

**Comment by joshiejack** [comment]
No thanks!

You are not 'customers'. I made this mod because I want to play it. So it's not worth my time to work on things I'm not interested in using myself. Sorry.
