### ISSUE TITLE
[Minor Bug] Farming Stations and Planters Place "Any Seed" Blocks

### ISSUE THREAD

**Issue by brbrainerd** [joshiejack/Harvest-Moon#119]
Greetings!  First off, let me say that I love your mod.  The mechanics that you have carried over from Harvest Moon are MUCH more rewarding than vanilla farming methods.  Kudos.  I've got a minor issue to report, which is that in some automatic farming systems, such as EnderIO's Farming Station or Progressive Automation's Planter, the seeds from Harvest Festival are accepted and planted.  However, they are planted in the world as an "Any Seed" untextured block, are immediately recognized as fully grown, and immediately harvested (dropping nothing) by multiple systems.  Forestry's Multiblock farms do not have this issue, as they use a whitelist, and therefore do not accept any your seeds into their inventories for use.

Presumably, this issue could be fixed by giving every seed a unique identifier, but I would imagine that there is a better way.  Also, I am curious: how do you feel about players automating your mod?  Is automatically harvesting and selling plants and animal products something you explicitly want to discourage or encourage?

---
* Latest Log Files:
[latest.txt](https://github.com/PenguinSquad/Harvest-Festival/files/665423/latest.txt)
[fml-client-latest.txt](https://github.com/PenguinSquad/Harvest-Festival/files/665424/fml-client-latest.txt)

* Harvest Festival Version: 1.10.2-0.5.22
* Forge Version: 12.18.2.2171
* EnderIO Version: 1.10.2-3.0.1.138_beta
* Progressive Automation Version: 1.10.2-1.6.53

**Comment by joshiejack** [comment]
As of right now the mod isn't intended to be automatable. Except for watering crops. It goes against the purpose of the mod. As seen under my plans, I do plan to have some way to automate some things eventually. But that it something that would cost gold and would be later gate. So I'm not really keen on just being able to automate everything right away, because the mod is about caring for your crops/animals, not mass production with machines.
