### ISSUE TITLE
[suggestion] Modpack Compatibility

### ISSUE THREAD

**Issue by Chromogen** [joshiejack/Harvest-Moon#121]
Hey there,

just wondering if you could change some little things to ensure modpack compatibillity:

first thing
let HF have an option to have its own wheat / potatoe /vanilla crops
this would would be really helpful in terms of mod seperation since some mods rely on ludicricious amounts of crops and insane money production with automation / blacklisting crops seems to take alot of immersion from the mod

the other thing
let it have its own powerbar on HF-tools only. 
With other mods hungerbar-drains can be countered to a point where the mod will get broken
with its own powerbar this would be way easier to handle :)

**Comment by joshiejack** [comment]
First: I'm not keen on this, I wanted to keep things more tied in than separate. But I understand what you mean. If I ever was (unlikely). I'd probably rename the vanilla ones to something like 'wild potato' or whatever. To distinguish them. Possibly even let you sell them still but maybe to just a npc and only a certain amount a day. Unlikely to happen though, just a thought.

Two: I originally had my own energy system but I didn't like it, and much prefer using food. It's something I haven't ruled out entirely though since it could work, but it just seems like adding another hardcore aspect which not 100% keen on.

**Comment by DcNdrew** [comment]
Chromogen:
B:"Drops from vanilla crops not sellable"

**Comment by ecoay** [comment]
I would like to throw in my 2 cents. 
Best of both worlds on the vanilla crops by incorporating a "seed bundle" block. Its only function is if you give it 9 seeds/vanilla crops it will give you a HF seed bundle of that type.

With this improvement json files in /crops/  where we can define what crops the seed block accepts  and /store/   Where we can define what can be sold and for how much. So for instance we can sell pams harvestcraft honey etc. 

^By doing above you can increase compatibility and immersion. Take agricraft for example. I personally have created json files for all the seeds in my pack from immersive engineering to actually additions to be compatible with json files.

**Comment by joshiejack** [comment]
@ecoay The first suggestion wouldn't work unless it had a cost to use. Otherwise you're just getting seeds for free. But nah, I do have a plan on what I'd like to do with that already.

As for json nah, i'm sticking with crafttweaker way, it's just easier for me to support than writing my own system. In 0.6 you can add support for crops with that, and you can already add stuff to stores in 0.5 using it.

**Comment by Slither88** [comment]
Could we possibly also get minetweaker support for what drops from each of the nodes in the mines? Would allow for some interesting modpacks.

**Comment by joshiejack** [comment]
Technically you should be able to edit the drops for the normal rocks at least with something that lets you edit loot tables. Granted doesn't help with the other nodes :P

**Comment by Slither88** [comment]
Hehe. I can attest to this. Even Progression has some trouble affecting a specific node. If you feel it would not break the mod, it would be awesome to have. But it is your mod/decision in the end and I (we the fans) will be happy with what you decide.
