### ISSUE TITLE
Share progress between players

### ISSUE THREAD

**Issue by zmbush** [joshiejack/Harvest-Moon#128]
Is there a way in SMP to share progress/money between two or more players? I want to play with a friend, but we don't want to each make our own towns.

**Comment by joshiejack** [comment]
No direct way, you can skip the tutorials though (don't need separate towns just talking to the npcs) and for money sharing atm you can buy/sell salt since it ships for its cost. I do not want to add teams, I want to keep things open ended. I do plan to add like a bank in the future though where you could deposit money and share it.
