### ISSUE TITLE
Animal particles, crop growing, and disappearing item bugs

### ISSUE THREAD

**Issue by LoganReadinger** [joshiejack/Harvest-Moon#129]
I am on the modpack of Farming Valley version 0.7.0 with version 5.22 of Harvest Festival. My friend is hosting a server of the same version that we both play on. Recently he left the server running for the night without us playing on it. Over the course of the night around 50 days/nights passed in-game. When we returned, all of our animals had black particle effects on them and we could not milk/sheer the cows and sheep. Our crops also would no longer grow, even if we watered them every day for over 20 days. Currently the season is still spring and we are on day 204. Like other people we also experienced the item deletion bug that is a result of Inventory Tweaks so we will likely disable it to fix the problem.

Server Log Latest: [fml-server-latest.txt](https://github.com/PenguinSquad/Harvest-Festival/files/740727/fml-server-latest.txt)

**Comment by joshiejack** [comment]
The particles are because your animals are sick because they haven't been fed. You can either heal them instantly with medicine or they should correct themselves within a few days if properly cared for. (I think, unless I made that change in the next version xD). Although that should only really happen if the chunks with the animals in were loaded somehow. Did you turn the crops dying if not watered config on? The default is for that to be off. Otherwise I'm not sure what happened with the crops.

**Comment by joshiejack** [comment]
I fixed crops in latest 0.5. Dissappearing has existing issue so closing.
