### ISSUE TITLE
Flickering natural lighting when/after raining with shaders

### ISSUE THREAD

**Issue by ghost** [joshiejack/Harvest-Moon#133]
I use Optifine 1.10.2_HD_U_D4 to get shader support, and use Sildurs Vibrant Shaders v1.161 (also happens on 1.153) Medium for the actual shader settings. Forge 12.18.2.2171 and Harvest Festival 0.5.22.

Whenever it's raining, natural light starts flickering constantly (not torches etc, but sunlight). When it stops, flickering remains. 
![giphy](https://cloud.githubusercontent.com/assets/25546019/22617671/fb782b40-eaca-11e6-9a06-1ca3ac5c9ac4.gif)

Only happens with Harvest Festival installed, as my HF modpack is a direct duplicate of another one with only HF added. Other one doesn't have the problem. Had the same issue in the Farming Valley modpack where I added optifine and the shader to the stock pack. 

PS: Harvest Valley ignores Optifine weather and rain settings.

**Comment by melekaiah** [comment]
got this one too. just tested with and without harvest festival. gonna test some more. cause if this is hte cause i will have to remove harvest festival. we will have to rebuild stuff :(

**Comment by joshiejack** [comment]
I changed something in 0.6 with rain. Can someone test if it still occurs. If it does I'm even more clueless.

**Comment by honestabelink** [comment]
I can confirm too that the issue is present on Harvest Festival 0.5.22

Tested on
OptiFine_1.10.2_HD_U_D4|OptiFine_1.10.2_HD_U_D7
forge-1.10.2-12.18.2.2171|forge-1.10.2-12.18.3.2185
Sildurs Vibrant Shaders v1.163 Medium

Building from source, your changes appear to correct the issue. Again tested on all above scenarios.

Good work 👍 
Looking forward to future releases
