### ISSUE TITLE
Chicken stopped doing anything at all.

### ISSUE THREAD

**Issue by Lance5057** [joshiejack/Harvest-Moon#14]
My chicken is no longer able to be fed, won't move at all, and hasn't laid eggs at all (though I'm assuming its probably still too young). I tried giving it medicine thinking maybe i forgot to feed it, and it took the meds but nothing changed. It just stands still and makes sounds.

**Comment by joshiejack** [comment]
Which build is this. I did something with the ai a couple hours ago.

**Comment by Lance5057** [comment]
1.10.2-0.5.0-28

**Comment by joshiejack** [comment]
Yeah, literally did things in 32. Increased the range, and allowed to chickens to actually walk some, instead of waiting to be fed before walking xD.

**Comment by Lance5057** [comment]
Well it's definitely moving now but it still won't accept food or lay eggs.

**Comment by joshiejack** [comment]
Literally played with them on server and fine for me. Only way it couldn't be fed is if it ate already that day. And it won't lay if sick or hungry. Did you wait until the new day?

**Comment by Lance5057** [comment]
Yup, been several days now, still wont take any food.

**Comment by Lance5057** [comment]
I went another 2 days and now it eats again. I guess it just didn't want to eat for that week.

**Comment by joshiejack** [comment]
Strange, did you have a feeding tray down with food in it? Although if you did, dunno why you'd be feeding by hand. I'll have to test myself some more.

**Comment by Lance5057** [comment]
I had no feeding trays yet no, was my first chicken.

**Comment by joshiejack** [comment]
Ok after doing some further testing. I can't confirm the not being fed part. Well so far anyway. Egg part makes sense, if he was hungry/sick. I've made healing animals fully heal them now, which I'm guessing yours was sick, why he wasn't producing. Before it would take like a couple medicine to heal. Also made it so animals will gain health if they've been looked after each day. Instead of just staying sick forever...
