### ISSUE TITLE
Tooltip for shipping prices?

### ISSUE THREAD

**Issue by LeeHuangChen** [joshiejack/Harvest-Moon#202]
First of all, I just want to say that I really enjoy playing with your mod!  Thank you so much for spending the effort and time!

Just one minor suggestion, do you think it would be possible for the player to get sell price of crops/meals they have in their inventory before they put it in the shipping bin?  I'm having trouble figuring out how much everything costs by keeping track of how much gold I have before and after I sleep.

I have thought about implementing this myself using minetweaker tooltips, however I don't know the pricing of all of the recipes. 

Thank you so much for your time and consideration!

**Comment by GirafiStudios** [comment]
Thanks for your suggestion.
Having the prices show up in the tooltip is not something HF would wanna do, since you are meant to "discover" the prices. When you have shipped something, you can lookup the price in the "Farming for Dummies" book (Added in HF 0.6+).
If you really want a tooltip, you can turn on debug mode and that will show the prices in the tooltip
