### ISSUE TITLE
Endless unstoppable rain

### ISSUE THREAD

**Issue by LemADEC** [joshiejack/Harvest-Moon#42]
As of Harvest-Festival-1.10.2-0.5.2 with forge-1.10.2-12.18.1.2092, it appears we're unable to stop the endless rain during Spring season.
We've experienced constant rain twice during Spring season. Using server command had no effect on stopping it.
Rain doesn't start immediately during Spring but once started it feels like only Summer season will stop it.

What's the current expected behavior for rain? How can we influence it without completely removing it?

**Comment by joshiejack** [comment]
Weather is calculated 7 days ahead. And the weather for the day is for the
whole day. What commands were you trying weather set clear and hf weather
sunny both work for me. I forgot to override toggledownfall but those two
should work. If you've had it constant then i guess that's just good luckm

**Comment by LemADEC** [comment]
I was trying with /weather clear.

I've now tried /hf weather rain and it did start the rain.
Using /weather clear didn't stop it.
Using /hf weather sunny did stop it.
Using /minecraft:weather clear did stop it.
Looks like Nucleus is messing around with the weather command handling.

**Comment by GirafiStudios** [comment]
I'm glad you figured it out!
I just tried /weather clear and it works just fine for me, maybe you ran the commands too fast?

**Comment by LemADEC** [comment]
I've been lagging due to rain for several days, trust me when I tried that command quite a few time, speed isn't the issue here.

**Comment by LemADEC** [comment]
https://github.com/NucleusPowered/Nucleus/issues/400

**Comment by GirafiStudios** [comment]
Does it work with Nucleus?

**Comment by joshiejack** [comment]
It's not really a bug with nucleus I'd think. Since I change how weather is handled, so that I can support prediction of the weather.

**Comment by LemADEC** [comment]
something doesn't interact well between Harvest Festival and Nucleus. Any idea how to fix it?

**Comment by GirafiStudios** [comment]
You would have to track down that "something". It could be Sponge, since I noticed you were using that.

**Comment by dualspiral** [comment]
Nucleus doesn't mess around with the weather handling. All I do is ask Sponge to set the weather for me.

@LemADEC - as @joshiejack points to, this mod changes the way the weather works. The reason `/minecraft:weather` works is because [HF actually (quite rightly) changes that command here](https://github.com/PenguinSquad/Harvest-Festival/blob/1.10.2/src/main/java/joshie/harvest/core/commands/VanillaCommands.java#L53-L71). So, `/minecraft:weather` becomes similar to `/hf weather`.

Sponge, when trying to set the weather, does what [vanilla minecraft's weather command would do](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L1772-L1863), which is why Nucleus doesn't work.

However, the workaround here is to turn off Nucleus' weather command. If you would rather use Nucleus' permissions for that command, then I suspect I could come up with some way to allow you to use Nucleus permissions with the base command,

**Comment by LemADEC** [comment]
I'm not quite sure why Sponge rewrite vanilla code instead of referencing it so it's more compatible with mods.
