### ISSUE TITLE
Crashing on Server

### ISSUE THREAD

**Issue by Rozzers** [joshiejack/Harvest-Moon#89]
My friends and I are playing this on a server and the server crashes randomly since last update.

This is the crash report
[crash-2016-10-21_22.29.34-server.txt](https://github.com/PenguinSquad/Harvest-Festival/files/545627/crash-2016-10-21_22.29.34-server.txt)

This is the log before crash
[2016-10-21-3.txt](https://github.com/PenguinSquad/Harvest-Festival/files/545629/2016-10-21-3.txt)

I'm only assuming its a Harvest Festival issue because of the errors I get right before it crashes.

**Comment by joshiejack** [comment]
It's probably not random but rather when the new day ticks over and a certain person hasn't been online. Easy enough for me to fix. It wouldn't have crashed before as the data would have been loaded for them. At least if I understand it correctly. 

(You can always in the mean time find the person with an incubator and remove it)

**Comment by joshiejack** [comment]
Try this one http://joshiejack.uk/mods/Harvest-Festival-1.10.2-0.5.13.jar

**Comment by Rozzers** [comment]
I've updated it. I'm gonna let it run for a while and see if it crashes.

**Comment by Rozzers** [comment]
I am now getting a spam of harvest uuid already existing. Let me know if I need a new issue claim for this.

[latest.txt](https://github.com/PenguinSquad/Harvest-Festival/files/546689/latest.txt)

**Comment by joshiejack** [comment]
Not really much I can do about this. I'm not doing anything, this is something that tends to happen with entities that persist. (https://bugs.mojang.com/browse/MC-95649) All I can think of doing is asming out the vanilla error message, but that doesn't really solve anything. You could take drastic measure and try killing the entities that are throwing that message. 

_Hmmm, looking at that it looks like it's happening when the day ticks over, i wonder._
_I wonder if that's related it to loading chunks when placing the rocks/stone, then unloading them_
_So that the entities get loaded/unloaded and therefore spamming the vanilla message once a day_

**Yep from test can confirm that this is caused by rapid loading/unloading of chunks whenever the day ticks over, due to things like soil being dried out, animals being updated and towns spawning blocks. I'll add a check for if the chunk is loaded to perform these actions. Which may cause some funny issues but will have to see**

**Comment by joshiejack** [comment]
Ok try this one, if this doesn't work, you'll just have to kill the entities. You WILL still  see the messages occasionally because that's just how it works in vanilla, but it shouldn't be loading towns etc in unloaded chunks now.

http://joshiejack.uk/mods/Harvest-Festival-1.10.2-0.5.14.jar

**Comment by Rozzers** [comment]
Ok. It's nice to not have it spamming. What are the drawbacks to not loading the towns in the unloaded chunks?

**Comment by joshiejack** [comment]
Nothing bad just means the wood/stones don't get moved, animals/crops won't accidentally get loaded and possibly update. Although idk if it made them update or not.

**Comment by Rozzers** [comment]
I see. We will play around and see what happens. Thanks for the help Joshie!

Edit: Seems to be working fine. Thanks!
