### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Kusark** [joshiejack/Harvest-Moon#90]
https://gist.github.com/Komandoe/b06b3c04bbcf5e5881886ae646b154e8

**Comment by joshiejack** [comment]
There's no crash in that report.

**Comment by Kusark** [comment]
Jk thats the game output, here is the log https://gist.github.com/Komandoe/ac4e3ff18e5befdbbc035c90a9994441

**Comment by Kusark** [comment]
It is crashing, I just don't know why. Im not using any other mod, just the latest forge and your mod's latest version

**Comment by Kusark** [comment]
Oh wait, it's not generating a crash report. Just logs. But it always crashes whenever it's almost done loading up??

**Comment by joshiejack** [comment]
Yeah without the actual crash report, i can't help. Are you looking in the right folders for it?

**Comment by Kusark** [comment]
The crash report folder doesnt have any reports from 10/22/16

**Comment by Kusark** [comment]
Well IDK what I'm supposed to say if there's no crash report.

**Comment by joshiejack** [comment]
I'm supposed to just guess what your issue is? Is there ANYTHING displayed when you actually crash. What client are you using to play the mod?

**Comment by Kusark** [comment]
I'm using Forge 1.10.2 12.18.2.2099 and whenever the mod is almost done loading it says "Java Platform SE Binary has stopped working". Then it crashes, generates a log, and goes back to the launcher. I don't know what else I'm supposed to say if that's all there is to it, lol. I'm using the latest Java, I've got 3G allocated. It always crashes right when the resource manager starts loading up. That's all I know. I can't give info that doesn't exist.

**Comment by joshiejack** [comment]
Which launcher is it, is what i asked.

**Comment by Kusark** [comment]
Minecraft Launcher 1.6.61

**Comment by joshiejack** [comment]
This may be farfetched but perhaps you could record the process or send screenshots of each bit, because I've literally nothing to go off here. You're literally just telling me "I run the game, it crashes" and then you're giving me logs about the startup of the game rather than the crash itself.

(Either way this is all 100% user error, because everyone else is loading just fine) I'm not really hear to debug this kinda thing, but things with the mod, but whatever.

**Comment by Kusark** [comment]
I'm saying "I run the game, it crashes" because 1. That's all I know 2. That's literally the only info I have. 

OBS isn't working, so I just took screenshots instead. Here they are:

I open the launcher - http://imgur.com/a/pW6Pk (It says 1.6.66 because the launcher just updated today)

I check the mod folder to make sure the mod is there - http://imgur.com/a/cFM9q

I close it all out and I hit play.  Then the game stops here - http://imgur.com/a/yNbHI

And then a window pops up saying this - http://imgur.com/a/PYC0y

I hit close program, and it takes me back to the launcher - http://imgur.com/a/izVSQ

That's all I know. I can't give a crash log that doesn't exist. It always just crashes at that one specific point. I've got latest forge, latest version of the mod, latest java and latest launcher.

**Comment by joshiejack** [comment]
Literally unable to help you then. I'm afraid you're on your own.

**Comment by Kusark** [comment]
Quality support, thanks.

**Comment by joshiejack** [comment]
You really expect help when all you are able to tell me is "it crashes". Especially when other people are able to load up just fine. I'm not a magical fairy that can tell what's going on. Sure if you were using java 6 rather than java 8 i could help, sure if you didn't have enough memory assigned i could help, sure if you were using outdated versions i could help, sure if i had something that actually pointed to an issue with my mod i could help, but not what I have absolutely nothing to go off.
