### ISSUE TITLE
Yulif The Carpenter disappeared

### ISSUE THREAD

**Issue by TheDarkPreacher** [joshiejack/Harvest-Moon#92]
So, was playing, and Yulif was building the cafe, and he got stuck on a block while trying to path. I hit him with an open hand because I couldn't get to him to push him out of the block, and he disappeared. he didn't respawn at the carpenter's house, and I can't even spawn him back in creatively. I go to place down the Yulif Spawn item, and nothing happens. So now i have no carpenter, and an unfinished cafe. using version 0.5.12 when he first disappeared, tried updating to 0.5.13, but he's still missing. do i need to build a new carpenter's house outside of the village or is there a command or something to recall Yulif?

**Comment by joshiejack** [comment]
If he didn't actually die then he won't respawn. The npc spawning item should only fail if there's a yulif already around. Try the /hf npc command and see if he's listed. God knows why he randomly disappeared, i guess i should make the item always spawn him, I didn't before because you tended to end up spawning two.

NPCs are getting really annoying. I've got people reporting them disappointing and others saying they keep duplicating >.>, why can't they just work! D=  (never had either happen to me)

**Comment by TheDarkPreacher** [comment]
Found him! He had teleported to a cave right below the cafe. 20 blocks below the cafe, in fact, which is kinda a good thing, because I found a really cool cave system.

**Comment by TheDarkPreacher** [comment]
I just killed him with my sword and he went right back to the carpenter's house like he's supposed to. pushed him a bit and off he went.

**Comment by joshiejack** [comment]
Hehe, glad you found him. Dunno why he teleported down but not back up.
