### ISSUE TITLE
Spam in the Server Console

### ISSUE THREAD

**Issue by MainFreak** [joshiejack/Harvest-Moon#98]
I am not sure if this is intended, but I am curious why my server console is always spammed with this. I had this since I first added Harvest Festival and it is still present. If this is a bug, I would ask you to fix this if possible since it makes scanning the console really hard. Also sometimes there are two Yulifs. Both of this events happen when multiple villages are set up ( even when the required distance set in the config is respected this happens )
![img_20161030_022421](https://cloud.githubusercontent.com/assets/20734190/19833607/54c9ecc6-9e48-11e6-9fc4-e80579f46bcd.png)

**Comment by GirafiStudios** [comment]
Already addressed in https://github.com/PenguinSquad/Harvest-Festival/issues/89 and a solution was found to it :)

**Comment by joshiejack** [comment]
This happens when vanilla persists an entity. Which version are you on.

**Comment by MainFreak** [comment]
One of the most recent ones. Will update tomorrow. If it still happens I will reply to this

**Comment by joshiejack** [comment]
Yeah since it's happening every 20 minutes aka when a new day starts, more than likely because it's doing the loading of chunks/unloading when placing/removing logs or rocks, which loads/unloads the entity. The message is an annoying vanilla one. I stopped the ticking of towns that are unloaded in latest, should just mean those blocks won't change unless something is loading the chunk.
